### ISSUE TITLE
[🚀 Feature]

### ISSUE THREAD

**Issue by PedroS235** [snt-arg/robot_suite#2]
Develop a package `robot_capabilities`, which is responsible for reading a configuration file defining a robot capabiti and offering this as a service.

For example, a capability config example:

```yaml
robot_type: aerial
robot_name: tello
capabilities:
  land:
    description: A service which lands the drone
  takeoff:
    description: A service which take off the drone
  movement:
    description: A topic which receives velocity commands, both linear and angular
    topic_name: /cmd_vel
    type: geometry_msgs/msg/Twist
    interface: "{linear: {x:value,y:value,z:value}, angular:{x:value,y:value,z:value, heigh: value}"
```
